---
source: docker
container_name:
  - nexus-traefik
  - nexus-nginx-pm
  - nexus-app
labels:
  type: traefik
---
source: docker
container_name:
  - nexus-lldap
  - nexus-keycloak
labels:
  type: syslog
