export const PHONE_CODES = [
  { code: '+1',   flag: '🇺🇸', country: 'United States' },
  { code: '+1',   flag: '🇨🇦', country: 'Canada' },
  { code: '+7',   flag: '🇷🇺', country: 'Russia' },
  { code: '+20',  flag: '🇪🇬', country: 'Egypt' },
  { code: '+27',  flag: '🇿🇦', country: 'South Africa' },
  { code: '+30',  flag: '🇬🇷', country: 'Greece' },
  { code: '+31',  flag: '🇳🇱', country: 'Netherlands' },
  { code: '+32',  flag: '🇧🇪', country: 'Belgium' },
  { code: '+33',  flag: '🇫🇷', country: 'France' },
  { code: '+34',  flag: '🇪🇸', country: 'Spain' },
  { code: '+36',  flag: '🇭🇺', country: 'Hungary' },
  { code: '+39',  flag: '🇮🇹', country: 'Italy' },
  { code: '+40',  flag: '🇷🇴', country: 'Romania' },
  { code: '+41',  flag: '🇨🇭', country: 'Switzerland' },
  { code: '+43',  flag: '🇦🇹', country: 'Austria' },
  { code: '+44',  flag: '🇬🇧', country: 'United Kingdom' },
  { code: '+45',  flag: '🇩🇰', country: 'Denmark' },
  { code: '+46',  flag: '🇸🇪', country: 'Sweden' },
  { code: '+47',  flag: '🇳🇴', country: 'Norway' },
  { code: '+48',  flag: '🇵🇱', country: 'Poland' },
  { code: '+49',  flag: '🇩🇪', country: 'Germany' },
  { code: '+51',  flag: '🇵🇪', country: 'Peru' },
  { code: '+52',  flag: '🇲🇽', country: 'Mexico' },
  { code: '+53',  flag: '🇨🇺', country: 'Cuba' },
  { code: '+54',  flag: '🇦🇷', country: 'Argentina' },
  { code: '+55',  flag: '🇧🇷', country: 'Brazil' },
  { code: '+56',  flag: '🇨🇱', country: 'Chile' },
  { code: '+57',  flag: '🇨🇴', country: 'Colombia' },
  { code: '+58',  flag: '🇻🇪', country: 'Venezuela' },
  { code: '+60',  flag: '🇲🇾', country: 'Malaysia' },
  { code: '+61',  flag: '🇦🇺', country: 'Australia' },
  { code: '+62',  flag: '🇮🇩', country: 'Indonesia' },
  { code: '+63',  flag: '🇵🇭', country: 'Philippines' },
  { code: '+64',  flag: '🇳🇿', country: 'New Zealand' },
  { code: '+65',  flag: '🇸🇬', country: 'Singapore' },
  { code: '+66',  flag: '🇹🇭', country: 'Thailand' },
  { code: '+81',  flag: '🇯🇵', country: 'Japan' },
  { code: '+82',  flag: '🇰🇷', country: 'South Korea' },
  { code: '+84',  flag: '🇻🇳', country: 'Vietnam' },
  { code: '+86',  flag: '🇨🇳', country: 'China' },
  { code: '+90',  flag: '🇹🇷', country: 'Turkey' },
  { code: '+91',  flag: '🇮🇳', country: 'India' },
  { code: '+92',  flag: '🇵🇰', country: 'Pakistan' },
  { code: '+93',  flag: '🇦🇫', country: 'Afghanistan' },
  { code: '+94',  flag: '🇱🇰', country: 'Sri Lanka' },
  { code: '+95',  flag: '🇲🇲', country: 'Myanmar' },
  { code: '+98',  flag: '🇮🇷', country: 'Iran' },
  { code: '+212', flag: '🇲🇦', country: 'Morocco' },
  { code: '+213', flag: '🇩🇿', country: 'Algeria' },
  { code: '+216', flag: '🇹🇳', country: 'Tunisia' },
  { code: '+218', flag: '🇱🇾', country: 'Libya' },
  { code: '+220', flag: '🇬🇲', country: 'Gambia' },
  { code: '+221', flag: '🇸🇳', country: 'Senegal' },
  { code: '+222', flag: '🇲🇷', country: 'Mauritania' },
  { code: '+223', flag: '🇲🇱', country: 'Mali' },
  { code: '+224', flag: '🇬🇳', country: 'Guinea' },
  { code: '+225', flag: '🇨🇮', country: "Côte d'Ivoire" },
  { code: '+226', flag: '🇧🇫', country: 'Burkina Faso' },
  { code: '+227', flag: '🇳🇪', country: 'Niger' },
  { code: '+228', flag: '🇹🇬', country: 'Togo' },
  { code: '+229', flag: '🇧🇯', country: 'Benin' },
  { code: '+230', flag: '🇲🇺', country: 'Mauritius' },
  { code: '+231', flag: '🇱🇷', country: 'Liberia' },
  { code: '+232', flag: '🇸🇱', country: 'Sierra Leone' },
  { code: '+233', flag: '🇬🇭', country: 'Ghana' },
  { code: '+234', flag: '🇳🇬', country: 'Nigeria' },
  { code: '+235', flag: '🇹🇩', country: 'Chad' },
  { code: '+236', flag: '🇨🇫', country: 'Central African Republic' },
  { code: '+237', flag: '🇨🇲', country: 'Cameroon' },
  { code: '+238', flag: '🇨🇻', country: 'Cape Verde' },
  { code: '+240', flag: '🇬🇶', country: 'Equatorial Guinea' },
  { code: '+241', flag: '🇬🇦', country: 'Gabon' },
  { code: '+242', flag: '🇨🇬', country: 'Congo' },
  { code: '+243', flag: '🇨🇩', country: 'DR Congo' },
  { code: '+244', flag: '🇦🇴', country: 'Angola' },
  { code: '+245', flag: '🇬🇼', country: 'Guinea-Bissau' },
  { code: '+248', flag: '🇸🇨', country: 'Seychelles' },
  { code: '+249', flag: '🇸🇩', country: 'Sudan' },
  { code: '+250', flag: '🇷🇼', country: 'Rwanda' },
  { code: '+251', flag: '🇪🇹', country: 'Ethiopia' },
  { code: '+252', flag: '🇸🇴', country: 'Somalia' },
  { code: '+253', flag: '🇩🇯', country: 'Djibouti' },
  { code: '+254', flag: '🇰🇪', country: 'Kenya' },
  { code: '+255', flag: '🇹🇿', country: 'Tanzania' },
  { code: '+256', flag: '🇺🇬', country: 'Uganda' },
  { code: '+257', flag: '🇧🇮', country: 'Burundi' },
  { code: '+258', flag: '🇲🇿', country: 'Mozambique' },
  { code: '+260', flag: '🇿🇲', country: 'Zambia' },
  { code: '+261', flag: '🇲🇬', country: 'Madagascar' },
  { code: '+263', flag: '🇿🇼', country: 'Zimbabwe' },
  { code: '+264', flag: '🇳🇦', country: 'Namibia' },
  { code: '+265', flag: '🇲🇼', country: 'Malawi' },
  { code: '+266', flag: '🇱🇸', country: 'Lesotho' },
  { code: '+267', flag: '🇧🇼', country: 'Botswana' },
  { code: '+268', flag: '🇸🇿', country: 'Eswatini' },
  { code: '+269', flag: '🇰🇲', country: 'Comoros' },
  { code: '+291', flag: '🇪🇷', country: 'Eritrea' },
  { code: '+297', flag: '🇦🇼', country: 'Aruba' },
  { code: '+298', flag: '🇫🇴', country: 'Faroe Islands' },
  { code: '+299', flag: '🇬🇱', country: 'Greenland' },
  { code: '+350', flag: '🇬🇮', country: 'Gibraltar' },
  { code: '+351', flag: '🇵🇹', country: 'Portugal' },
  { code: '+352', flag: '🇱🇺', country: 'Luxembourg' },
  { code: '+353', flag: '🇮🇪', country: 'Ireland' },
  { code: '+354', flag: '🇮🇸', country: 'Iceland' },
  { code: '+355', flag: '🇦🇱', country: 'Albania' },
  { code: '+356', flag: '🇲🇹', country: 'Malta' },
  { code: '+357', flag: '🇨🇾', country: 'Cyprus' },
  { code: '+358', flag: '🇫🇮', country: 'Finland' },
  { code: '+359', flag: '🇧🇬', country: 'Bulgaria' },
  { code: '+370', flag: '🇱🇹', country: 'Lithuania' },
  { code: '+371', flag: '🇱🇻', country: 'Latvia' },
  { code: '+372', flag: '🇪🇪', country: 'Estonia' },
  { code: '+373', flag: '🇲🇩', country: 'Moldova' },
  { code: '+374', flag: '🇦🇲', country: 'Armenia' },
  { code: '+375', flag: '🇧🇾', country: 'Belarus' },
  { code: '+376', flag: '🇦🇩', country: 'Andorra' },
  { code: '+377', flag: '🇲🇨', country: 'Monaco' },
  { code: '+380', flag: '🇺🇦', country: 'Ukraine' },
  { code: '+381', flag: '🇷🇸', country: 'Serbia' },
  { code: '+382', flag: '🇲🇪', country: 'Montenegro' },
  { code: '+383', flag: '🇽🇰', country: 'Kosovo' },
  { code: '+385', flag: '🇭🇷', country: 'Croatia' },
  { code: '+386', flag: '🇸🇮', country: 'Slovenia' },
  { code: '+387', flag: '🇧🇦', country: 'Bosnia' },
  { code: '+389', flag: '🇲🇰', country: 'North Macedonia' },
  { code: '+420', flag: '🇨🇿', country: 'Czech Republic' },
  { code: '+421', flag: '🇸🇰', country: 'Slovakia' },
  { code: '+423', flag: '🇱🇮', country: 'Liechtenstein' },
  { code: '+501', flag: '🇧🇿', country: 'Belize' },
  { code: '+502', flag: '🇬🇹', country: 'Guatemala' },
  { code: '+503', flag: '🇸🇻', country: 'El Salvador' },
  { code: '+504', flag: '🇭🇳', country: 'Honduras' },
  { code: '+505', flag: '🇳🇮', country: 'Nicaragua' },
  { code: '+506', flag: '🇨🇷', country: 'Costa Rica' },
  { code: '+507', flag: '🇵🇦', country: 'Panama' },
  { code: '+509', flag: '🇭🇹', country: 'Haiti' },
  { code: '+591', flag: '🇧🇴', country: 'Bolivia' },
  { code: '+592', flag: '🇬🇾', country: 'Guyana' },
  { code: '+593', flag: '🇪🇨', country: 'Ecuador' },
  { code: '+595', flag: '🇵🇾', country: 'Paraguay' },
  { code: '+597', flag: '🇸🇷', country: 'Suriname' },
  { code: '+598', flag: '🇺🇾', country: 'Uruguay' },
  { code: '+670', flag: '🇹🇱', country: 'Timor-Leste' },
  { code: '+673', flag: '🇧🇳', country: 'Brunei' },
  { code: '+675', flag: '🇵🇬', country: 'Papua New Guinea' },
  { code: '+676', flag: '🇹🇴', country: 'Tonga' },
  { code: '+677', flag: '🇸🇧', country: 'Solomon Islands' },
  { code: '+678', flag: '🇻🇺', country: 'Vanuatu' },
  { code: '+679', flag: '🇫🇯', country: 'Fiji' },
  { code: '+685', flag: '🇼🇸', country: 'Samoa' },
  { code: '+686', flag: '🇰🇮', country: 'Kiribati' },
  { code: '+850', flag: '🇰🇵', country: 'North Korea' },
  { code: '+852', flag: '🇭🇰', country: 'Hong Kong' },
  { code: '+853', flag: '🇲🇴', country: 'Macau' },
  { code: '+855', flag: '🇰🇭', country: 'Cambodia' },
  { code: '+856', flag: '🇱🇦', country: 'Laos' },
  { code: '+880', flag: '🇧🇩', country: 'Bangladesh' },
  { code: '+886', flag: '🇹🇼', country: 'Taiwan' },
  { code: '+960', flag: '🇲🇻', country: 'Maldives' },
  { code: '+961', flag: '🇱🇧', country: 'Lebanon' },
  { code: '+962', flag: '🇯🇴', country: 'Jordan' },
  { code: '+963', flag: '🇸🇾', country: 'Syria' },
  { code: '+964', flag: '🇮🇶', country: 'Iraq' },
  { code: '+965', flag: '🇰🇼', country: 'Kuwait' },
  { code: '+966', flag: '🇸🇦', country: 'Saudi Arabia' },
  { code: '+967', flag: '🇾🇪', country: 'Yemen' },
  { code: '+968', flag: '🇴🇲', country: 'Oman' },
  { code: '+970', flag: '🇵🇸', country: 'Palestine' },
  { code: '+971', flag: '🇦🇪', country: 'UAE' },
  { code: '+972', flag: '🇮🇱', country: 'Israel' },
  { code: '+973', flag: '🇧🇭', country: 'Bahrain' },
  { code: '+974', flag: '🇶🇦', country: 'Qatar' },
  { code: '+975', flag: '🇧🇹', country: 'Bhutan' },
  { code: '+976', flag: '🇲🇳', country: 'Mongolia' },
  { code: '+977', flag: '🇳🇵', country: 'Nepal' },
  { code: '+992', flag: '🇹🇯', country: 'Tajikistan' },
  { code: '+993', flag: '🇹🇲', country: 'Turkmenistan' },
  { code: '+994', flag: '🇦🇿', country: 'Azerbaijan' },
  { code: '+995', flag: '🇬🇪', country: 'Georgia' },
  { code: '+996', flag: '🇰🇬', country: 'Kyrgyzstan' },
  { code: '+998', flag: '🇺🇿', country: 'Uzbekistan' },
];
